{
 "title": "Alerting Dashboard Test",
 "tags": [ "alerting" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(up, job)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"$job\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{job=\"$job\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(process_cpu_time_seconds_total{job=\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) * 100",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": ".NET Exception Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(process_runtime_dotnet_exceptions_count_total{job=\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", job=\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", http_route!~\"/metrics|/ready|/alive\"}[1m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}