{
 "title": "ASP.NET Core",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_active_requests,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_active_requests{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},pod)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\"},http_route)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", http_route=~\"$route\"},http_request_method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kestrel_active_connections{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"})",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range]))\r\n  )",
     "legendFormat": "Status {{`{{http_response_status_code}}`}}"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\", error_type!=\"\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range])))",
     "legendFormat": "{{`{{scheme}}`}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (label_replace(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range])), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")  )",
     "legendFormat": "{{`{{protocol}}`}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "  topk(10,  sum by (http_route, http_request_method, method_route) (    label_join(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route=~\"$route\", http_request_method=~\"$method\", http_route!=\"\"}[$__range])), \"method_route\", \" \", \"http_request_method\", \"http_route\")  ))",
     "legendFormat": "{{`{{route}}}}`}}"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "  topk(10,  sum by (http_route, http_request_method, method_route) (    label_join(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", pod=~\"$pod\", http_route!=\"\", error_type!=\"\"}[$__range])), \"method_route\", \" \", \"http_request_method\", \"http_route\")  ))",
     "legendFormat": "{{`{{route}}`}}"
    }
   ]
  }
 ]
}